// Shared Pref

// const IS_FIRST_TIME = 'IS_FIRST_TIME';
// const IS_REMEMBER = 'IS_REMEMBER';
const fIRSTNAME = "FIRSTNAME";
const lASTNAME = "LASTNAME";
const uSERID = "USER_ID";
const uSERNATIVELANGUAGE = "USER_NATIVE_LANGUAGE";
const uSERENGLISHPROFICIENCY= "USER_ENGLISH_PROFICIENCY";
const dAYSSINCEINSTALL= "DAYS_SINCE_INSTALL";

// const SESSION_ID= "SESSION_ID";
// const GAME_NAME= "GAME_NAME";

const iSLOGIN = "IS_LOGIN";
const tOKEN = "TOKEN";
const pHONENUMBER = "PHONE_NUMBER";

// const IS_MUTE = "IS_MUTE";
const iSTTSPLAYING = "IS_TTS_PLAYING";
const pREVIOUSSENTENCE = "PREVIOUS_SENTENCE";



const fIREBASEANDROIDAPIKEY = 'AIzaSyCSh-qYWIG9DkJB0Uo_37AQVNvIQBvihtk';
const fIREBASEANDROIDAPPID = '1:197830150857:android:d4e0259542633989ff1b18';
const fIREBASEANDROIDMESSAGINGSENDERID ='197830150857';
const fIREBASEANDROIDPROJECTID ='mist-34b01';

// const GOOGLE_MAP_API_KEY ='';


const statusSuccess = 'User registered successfully';








