// Shared Pref

const IS_FIRST_TIME = 'IS_FIRST_TIME';
const IS_REMEMBER = 'IS_REMEMBER';
const FIRSTNAME = "FIRSTNAME";
const LASTNAME = "LASTNAME";
const USER_ID = "USER_ID";
const USER_NATIVE_LANGUAGE = "USER_NATIVE_LANGUAGE";
const USER_ENGLISH_PROFICIENCY= "USER_ENGLISH_PROFICIENCY";
const DAYS_SINCE_INSTALL= "DAYS_SINCE_INSTALL";

const SESSION_ID= "SESSION_ID";
const GAME_NAME= "GAME_NAME";

const IS_LOGIN = "IS_LOGIN";
const TOKEN = "TOKEN";
const PHONE_NUMBER = "PHONE_NUMBER";

const IS_MUTE = "IS_MUTE";
const IS_TTS_PLAYING = "IS_TTS_PLAYING";
const PREVIOUS_SENTENCE = "PREVIOUS_SENTENCE";



const FIREBASEANDROIDAPIKEY = 'AIzaSyCSh-qYWIG9DkJB0Uo_37AQVNvIQBvihtk';
const FIREBASEANDROIDAPPID = '1:197830150857:android:d4e0259542633989ff1b18';
const FIREBASEANDROIDMESSAGINGSENDERID ='197830150857';
const FIREBASEANDROIDPROJECTID ='mist-34b01';

const GOOGLE_MAP_API_KEY ='';

// const FIREBASEIOSAPIKEY = 'AIzaSyCY5DQ73GU_NMCjfdABkf_f172EJ_K5Y9s';
// const FIREBASEIOSAPPID = '1:349682106028:ios:ca0b89efd13abc64e1e909';
// const FIREBASEIOSMESSAGINGSENDERID ='349682106028';
// const FIREBASEIOSPROJECTID ='zap-ai-1a07d';

const statusSuccess = 'User registered successfully';








